### ISSUE TITLE
不能和YYkit并存

### ISSUE THREAD

**Issue by ArthurCL** [StenpZ/SZKit#1]
项目中已经存在YYKit，pod导入后就报错了， 有些报错的宏属性就跟YYKit的名字一样

**Comment by StenpZ** [comment]
测试并没有报错
<img width="588" alt="2018-04-19 3 12 57" src="https://user-images.githubusercontent.com/20317253/38976657-82b066a8-4377-11e8-8165-cd92aab8dc63.png">

**Comment by StenpZ** [comment]
测试并没有报错
<img width="588" alt="2018-04-19 3 12 57" src="https://user-images.githubusercontent.com/20317253/38976716-b1828a2e-4377-11e8-9c7e-93f248e2b305.png">

**Comment by ArthurCL** [comment]
你好，很感谢你能回复我，我用pod导入之后，我的项目中有个pch文件，很多界面都会用到滚动视图和YYKit的model，我在pch文件中导入这两个文件后，SZKit的SZAdapter文件就报错了，里面的宽高属性和YYKit的宏命名一样了

**Comment by StenpZ** [comment]
你可以把SZKit下载下来，将库里面的kScreenWidth()改个名字替换掉就可以了。

**Comment by ArthurCL** [comment]
一般习惯用pod管理一些第三方的类库，容易管理项目

**Comment by StenpZ** [comment]
已经解决。
